on:
  pull_request:
    paths:
      - 'terraform/**'
    branches:
      - develop
      - staging
      - main
  push:
    paths:
      - 'terraform/**'
    branches:
      - develop
      - staging
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform_deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      branch: ${{steps.branch.outputs.lowercase}}
      session: ${{ env.AWS_SESSION_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Branch Name From Push
        id: branch-merge
        if: github.event_name == 'push'
        run: echo "branch=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Branch Name From PR
        id: branch-pr
        if: github.event_name == 'pull_request'
        run: echo "branch=${{github.event.pull_request.base.ref}}" >> $GITHUB_ENV

      - name: Branch Name Case Transformation
        id: branch
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ env.branch }}

      - name: Set Keys
        id: keys
        run: |
          echo "::set-output name=ROLE_SESSION_NAME::GithubDeploymentTomatoWarningComTerraform${{steps.branch.outputs.capitalized}}"
          echo "::set-output name=AWS_ACCOUNT_ID::${{secrets[format('AWS_{0}_ACCOUNT',steps.branch.outputs.uppercase)]}}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          role-to-assume: arn:aws:iam::${{steps.keys.outputs.AWS_ACCOUNT_ID}}:role/GithubDeploymentRole
          role-session-name: ${{steps.keys.outputs.ROLE_SESSION_NAME}}
          aws-region: us-east-2

      - name: Set TF Workspace ENV Variable
        id: tf_workspace
        working-directory: terraform
        run: echo "TF_WORKSPACE=${{ steps.branch.outputs.lowercase }}" >> $GITHUB_ENV

      - name: Install Terraform
        id: tf_install
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform Init
        id: tf_init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        id: tf_plan
        working-directory: terraform
        run: terraform plan -no-color -var-file="env.all.tfvars" -var-file="env.${{ steps.branch.outputs.lowercase }}.tfvars" -out="plan.txt"
        continue-on-error: true

      - name: Github PR Comment with Terraform Plan Detail
        if: github.event_name == 'pull_request'
        uses: robburger/terraform-pr-commenter@v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXPAND_SUMMARY_DETAILS: 'false'
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.tf_plan.outputs.stdout, steps.tf_plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.tf_plan.outputs.exitcode }}

      - name: Terraform Plan Failed - Halt Operation
        id: tf_exit_on_failure
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply on Push
        id: tf_apply
        if: github.event_name == 'push'
        working-directory: terraform
        run: terraform apply plan.txt
